"""
src/ode_solver/problems.py
==========================
All ODE problem definitions: f(t, y) expressions and their exact solutions.
Each entry is a dict with keys: ode_type, f_expression, t0, y0, tf, exact_solution.
"""

ODE_PROBLEMS = [

        {"ode_type":"linear","f_expression":"-5.0","t0":0,"y0":1,"tf":1,"exact_solution":"-5.0*t + 1"},
        {"ode_type":"linear","f_expression":"-4.9","t0":0,"y0":2,"tf":1,"exact_solution":"-4.9*t + 2"},
        {"ode_type":"linear","f_expression":"-4.8","t0":0,"y0":3,"tf":1,"exact_solution":"-4.8*t + 3"},
        {"ode_type":"linear","f_expression":"-4.7","t0":0,"y0":4,"tf":1,"exact_solution":"-4.7*t + 4"},
        {"ode_type":"linear","f_expression":"-4.6","t0":0,"y0":5,"tf":1,"exact_solution":"-4.6*t + 5"},
        {"ode_type":"linear","f_expression":"-4.5","t0":0,"y0":6,"tf":1,"exact_solution":"-4.5*t + 6"},
        {"ode_type":"linear","f_expression":"-4.4","t0":0,"y0":7,"tf":1,"exact_solution":"-4.4*t + 7"},
        {"ode_type":"linear","f_expression":"-4.3","t0":0,"y0":8,"tf":1,"exact_solution":"-4.3*t + 8"},
        {"ode_type":"linear","f_expression":"-4.2","t0":0,"y0":9,"tf":1,"exact_solution":"-4.2*t + 9"},
        {"ode_type":"linear","f_expression":"-4.1","t0":0,"y0":10,"tf":1,"exact_solution":"-4.1*t + 10"},

        {"ode_type":"linear","f_expression":"-4.0","t0":0,"y0":1,"tf":1,"exact_solution":"-4.0*t + 1"},
        {"ode_type":"linear","f_expression":"-3.9","t0":0,"y0":2,"tf":1,"exact_solution":"-3.9*t + 2"},
        {"ode_type":"linear","f_expression":"-3.8","t0":0,"y0":3,"tf":1,"exact_solution":"-3.8*t + 3"},
        {"ode_type":"linear","f_expression":"-3.7","t0":0,"y0":4,"tf":1,"exact_solution":"-3.7*t + 4"},
        {"ode_type":"linear","f_expression":"-3.6","t0":0,"y0":5,"tf":1,"exact_solution":"-3.6*t + 5"},
        {"ode_type":"linear","f_expression":"-3.5","t0":0,"y0":6,"tf":1,"exact_solution":"-3.5*t + 6"},
        {"ode_type":"linear","f_expression":"-3.4","t0":0,"y0":7,"tf":1,"exact_solution":"-3.4*t + 7"},
        {"ode_type":"linear","f_expression":"-3.3","t0":0,"y0":8,"tf":1,"exact_solution":"-3.3*t + 8"},
        {"ode_type":"linear","f_expression":"-3.2","t0":0,"y0":9,"tf":1,"exact_solution":"-3.2*t + 9"},
        {"ode_type":"linear","f_expression":"-3.1","t0":0,"y0":10,"tf":1,"exact_solution":"-3.1*t + 10"},

        {"ode_type":"linear","f_expression":"-3.0","t0":0,"y0":1,"tf":1,"exact_solution":"-3.0*t + 1"},
        {"ode_type":"linear","f_expression":"-2.9","t0":0,"y0":2,"tf":1,"exact_solution":"-2.9*t + 2"},
        {"ode_type":"linear","f_expression":"-2.8","t0":0,"y0":3,"tf":1,"exact_solution":"-2.8*t + 3"},
        {"ode_type":"linear","f_expression":"-2.7","t0":0,"y0":4,"tf":1,"exact_solution":"-2.7*t + 4"},
        {"ode_type":"linear","f_expression":"-2.6","t0":0,"y0":5,"tf":1,"exact_solution":"-2.6*t + 5"},
        {"ode_type":"linear","f_expression":"-2.5","t0":0,"y0":6,"tf":1,"exact_solution":"-2.5*t + 6"},
        {"ode_type":"linear","f_expression":"-2.4","t0":0,"y0":7,"tf":1,"exact_solution":"-2.4*t + 7"},
        {"ode_type":"linear","f_expression":"-2.3","t0":0,"y0":8,"tf":1,"exact_solution":"-2.3*t + 8"},
        {"ode_type":"linear","f_expression":"-2.2","t0":0,"y0":9,"tf":1,"exact_solution":"-2.2*t + 9"},
        {"ode_type":"linear","f_expression":"-2.1","t0":0,"y0":10,"tf":1,"exact_solution":"-2.1*t + 10"},

        {"ode_type":"linear","f_expression":"-2.0","t0":0,"y0":1,"tf":1,"exact_solution":"-2.0*t + 1"},
        {"ode_type":"linear","f_expression":"-1.9","t0":0,"y0":2,"tf":1,"exact_solution":"-1.9*t + 2"},
        {"ode_type":"linear","f_expression":"-1.8","t0":0,"y0":3,"tf":1,"exact_solution":"-1.8*t + 3"},
        {"ode_type":"linear","f_expression":"-1.7","t0":0,"y0":4,"tf":1,"exact_solution":"-1.7*t + 4"},
        {"ode_type":"linear","f_expression":"-1.6","t0":0,"y0":5,"tf":1,"exact_solution":"-1.6*t + 5"},
        {"ode_type":"linear","f_expression":"-1.5","t0":0,"y0":6,"tf":1,"exact_solution":"-1.5*t + 6"},
        {"ode_type":"linear","f_expression":"-1.4","t0":0,"y0":7,"tf":1,"exact_solution":"-1.4*t + 7"},
        {"ode_type":"linear","f_expression":"-1.3","t0":0,"y0":8,"tf":1,"exact_solution":"-1.3*t + 8"},
        {"ode_type":"linear","f_expression":"-1.2","t0":0,"y0":9,"tf":1,"exact_solution":"-1.2*t + 9"},
        {"ode_type":"linear","f_expression":"-1.1","t0":0,"y0":10,"tf":1,"exact_solution":"-1.1*t + 10"},

        {"ode_type":"linear","f_expression":"-1.0","t0":0,"y0":1,"tf":1,"exact_solution":"-1.0*t + 1"},
        {"ode_type":"linear","f_expression":"-0.9","t0":0,"y0":2,"tf":1,"exact_solution":"-0.9*t + 2"},
        {"ode_type":"linear","f_expression":"-0.8","t0":0,"y0":3,"tf":1,"exact_solution":"-0.8*t + 3"},
        {"ode_type":"linear","f_expression":"-0.7","t0":0,"y0":4,"tf":1,"exact_solution":"-0.7*t + 4"},
        {"ode_type":"linear","f_expression":"-0.6","t0":0,"y0":5,"tf":1,"exact_solution":"-0.6*t + 5"},
        {"ode_type":"linear","f_expression":"-0.5","t0":0,"y0":6,"tf":1,"exact_solution":"-0.5*t + 6"},
        {"ode_type":"linear","f_expression":"-0.4","t0":0,"y0":7,"tf":1,"exact_solution":"-0.4*t + 7"},
        {"ode_type":"linear","f_expression":"-0.3","t0":0,"y0":8,"tf":1,"exact_solution":"-0.3*t + 8"},
        {"ode_type":"linear","f_expression":"-0.2","t0":0,"y0":9,"tf":1,"exact_solution":"-0.2*t + 9"},
        {"ode_type":"linear","f_expression":"-0.1","t0":0,"y0":10,"tf":1,"exact_solution":"-0.1*t + 10"},

        {"ode_type":"linear","f_expression":"0.0","t0":0,"y0":1,"tf":1,"exact_solution":"1"},
        {"ode_type":"linear","f_expression":"0.1","t0":0,"y0":2,"tf":1,"exact_solution":"0.1*t + 2"},
        {"ode_type":"linear","f_expression":"0.2","t0":0,"y0":3,"tf":1,"exact_solution":"0.2*t + 3"},
        {"ode_type":"linear","f_expression":"0.3","t0":0,"y0":4,"tf":1,"exact_solution":"0.3*t + 4"},
        {"ode_type":"linear","f_expression":"0.4","t0":0,"y0":5,"tf":1,"exact_solution":"0.4*t + 5"},
        {"ode_type":"linear","f_expression":"0.5","t0":0,"y0":6,"tf":1,"exact_solution":"0.5*t + 6"},
        {"ode_type":"linear","f_expression":"0.6","t0":0,"y0":7,"tf":1,"exact_solution":"0.6*t + 7"},
        {"ode_type":"linear","f_expression":"0.7","t0":0,"y0":8,"tf":1,"exact_solution":"0.7*t + 8"},
        {"ode_type":"linear","f_expression":"0.8","t0":0,"y0":9,"tf":1,"exact_solution":"0.8*t + 9"},
        {"ode_type":"linear","f_expression":"0.9","t0":0,"y0":10,"tf":1,"exact_solution":"0.9*t + 10"},

        {"ode_type":"linear","f_expression":"1.0","t0":0,"y0":1,"tf":1,"exact_solution":"1.0*t + 1"},
        {"ode_type":"linear","f_expression":"1.1","t0":0,"y0":2,"tf":1,"exact_solution":"1.1*t + 2"},
        {"ode_type":"linear","f_expression":"1.2","t0":0,"y0":3,"tf":1,"exact_solution":"1.2*t + 3"},
        {"ode_type":"linear","f_expression":"1.3","t0":0,"y0":4,"tf":1,"exact_solution":"1.3*t + 4"},
        {"ode_type":"linear","f_expression":"1.4","t0":0,"y0":5,"tf":1,"exact_solution":"1.4*t + 5"},
        {"ode_type":"linear","f_expression":"1.5","t0":0,"y0":6,"tf":1,"exact_solution":"1.5*t + 6"},
        {"ode_type":"linear","f_expression":"1.6","t0":0,"y0":7,"tf":1,"exact_solution":"1.6*t + 7"},
        {"ode_type":"linear","f_expression":"1.7","t0":0,"y0":8,"tf":1,"exact_solution":"1.7*t + 8"},
        {"ode_type":"linear","f_expression":"1.8","t0":0,"y0":9,"tf":1,"exact_solution":"1.8*t + 9"},
        {"ode_type":"linear","f_expression":"1.9","t0":0,"y0":10,"tf":1,"exact_solution":"1.9*t + 10"},

        {"ode_type":"linear","f_expression":"2.0","t0":0,"y0":1,"tf":1,"exact_solution":"2.0*t + 1"},
        {"ode_type":"linear","f_expression":"2.1","t0":0,"y0":2,"tf":1,"exact_solution":"2.1*t + 2"},
        {"ode_type":"linear","f_expression":"2.2","t0":0,"y0":3,"tf":1,"exact_solution":"2.2*t + 3"},
        {"ode_type":"linear","f_expression":"2.3","t0":0,"y0":4,"tf":1,"exact_solution":"2.3*t + 4"},
        {"ode_type":"linear","f_expression":"2.4","t0":0,"y0":5,"tf":1,"exact_solution":"2.4*t + 5"},
        {"ode_type":"linear","f_expression":"2.5","t0":0,"y0":6,"tf":1,"exact_solution":"2.5*t + 6"},
        {"ode_type":"linear","f_expression":"2.6","t0":0,"y0":7,"tf":1,"exact_solution":"2.6*t + 7"},
        {"ode_type":"linear","f_expression":"2.7","t0":0,"y0":8,"tf":1,"exact_solution":"2.7*t + 8"},
        {"ode_type":"linear","f_expression":"2.8","t0":0,"y0":9,"tf":1,"exact_solution":"2.8*t + 9"},
        {"ode_type":"linear","f_expression":"2.9","t0":0,"y0":10,"tf":1,"exact_solution":"2.9*t + 10"},

        {"ode_type":"linear","f_expression":"3.0","t0":0,"y0":1,"tf":1,"exact_solution":"3.0*t + 1"},
        {"ode_type":"linear","f_expression":"3.1","t0":0,"y0":2,"tf":1,"exact_solution":"3.1*t + 2"},
        {"ode_type":"linear","f_expression":"3.2","t0":0,"y0":3,"tf":1,"exact_solution":"3.2*t + 3"},
        {"ode_type":"linear","f_expression":"3.3","t0":0,"y0":4,"tf":1,"exact_solution":"3.3*t + 4"},
        {"ode_type":"linear","f_expression":"3.4","t0":0,"y0":5,"tf":1,"exact_solution":"3.4*t + 5"},
        {"ode_type":"linear","f_expression":"3.5","t0":0,"y0":6,"tf":1,"exact_solution":"3.5*t + 6"},
        {"ode_type":"linear","f_expression":"3.6","t0":0,"y0":7,"tf":1,"exact_solution":"3.6*t + 7"},
        {"ode_type":"linear","f_expression":"3.7","t0":0,"y0":8,"tf":1,"exact_solution":"3.7*t + 8"},
        {"ode_type":"linear","f_expression":"3.8","t0":0,"y0":9,"tf":1,"exact_solution":"3.8*t + 9"},
        {"ode_type":"linear","f_expression":"3.9","t0":0,"y0":10,"tf":1,"exact_solution":"3.9*t + 10"},


    # --- Basic linear ---
    {"ode_type": "linear", "f_expression": "2"                   , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "2*t + 1"},
    {"ode_type": "linear", "f_expression": "-y"                  , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-t)"},
    {"ode_type": "linear", "f_expression": "y"                   , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t)"},
    {"ode_type": "linear", "f_expression": "-y + 1"              , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "1 - exp(-t)"},
    {"ode_type": "linear", "f_expression": "sin(t)"              , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "1 - cos(t)"},
    {"ode_type": "linear", "f_expression": "-0.5*y"              , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-0.5*t)"},
    {"ode_type": "linear", "f_expression": "-y + t"              , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "t - 1 + exp(-t)"},
    {"ode_type": "linear", "f_expression": "-cos(t)*y"           , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-sin(t))"},
    {"ode_type": "linear", "f_expression": "-y/(1+t)"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1/(1+t)"},
    {"ode_type": "linear", "f_expression": "-y + exp(-t)"        , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "t*exp(-t)"},
    {"ode_type": "linear", "f_expression": "(1+t)*y"             , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t + t**2/2)"},
    {"ode_type": "linear", "f_expression": "y - t**2"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "t**2 + 2*t + 2 - exp(t)"},
    {"ode_type": "linear", "f_expression": "t*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t**2/2)"},
    {"ode_type": "linear", "f_expression": "-2*y + t**2"         , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "0.5*t**2 - 0.5*t + 0.25 + 1.75*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "y + exp(-t)"         , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "0.5*(exp(t) - exp(-t))"},
    {"ode_type": "linear", "f_expression": "-y + cos(t)"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "0.5*(sin(t) + cos(t)) + 0.5*exp(-t)"},

    # --- Simple exponential growth/decay ---
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "3*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(3*t)"},
    {"ode_type": "linear", "f_expression": "-3*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-3*t)"},
    {"ode_type": "linear", "f_expression": "0.3*y"               , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(0.3*t)"},
    {"ode_type": "linear", "f_expression": "-4*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-4*t)"},

    # --- Linear with polynomial forcing ---
    {"ode_type": "linear", "f_expression": "-y + t**2"           , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "t**2 - 2*t + 2 - 2*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y + t"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "t - 1 + 2*exp(-t)"},
    {"ode_type": "linear", "f_expression": "y + t"               , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "exp(t) - t - 1"},
    {"ode_type": "linear", "f_expression": "-2*y + t"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "0.5*t - 0.25 + 1.25*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "-y + sin(t)"         , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "0.5*(sin(t) - cos(t)) + 0.5*exp(-t)"},

    # --- Trigonometric coefficients ---
    {"ode_type": "linear", "f_expression": "cos(t)*y"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(sin(t))"},
    {"ode_type": "linear", "f_expression": "-sin(t)*y"           , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(cos(t)-1)"},
    {"ode_type": "linear", "f_expression": "2*cos(t)*y"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(2*sin(t))"},

    # --- Polynomial coefficients ---
    {"ode_type": "linear", "f_expression": "t*y"                 , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(t**2/2)"},
    {"ode_type": "linear", "f_expression": "-t*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-t**2/2)"},
    {"ode_type": "linear", "f_expression": "t**2*y"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t**3/3)"},
    {"ode_type": "linear", "f_expression": "-t**2*y"             , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-t**3/3)"},

    # --- Rational (integrating factor) ---
    {"ode_type": "linear", "f_expression": "y/(1+t)"             , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1+t"},
    {"ode_type": "linear", "f_expression": "-2*y/(1+t)"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1/(1+t)**2"},
    {"ode_type": "linear", "f_expression": "y/(2+t)"             , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*(2+t)/2"},

    # --- Exponential forcing ---
    {"ode_type": "linear", "f_expression": "-y + exp(t)"         , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "0.5*(exp(t) - exp(-t))"},
    {"ode_type": "linear", "f_expression": "y + exp(t)"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1.5*exp(t) - 0.5*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-2*y + exp(-t)"      , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "exp(-t) - exp(-2*t)"},

    # --- Mixed types ---
    {"ode_type": "linear", "f_expression": "2*y + t"             , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1.5*exp(2*t) - 0.5*t - 0.25"},
    {"ode_type": "linear", "f_expression": "-3*y + t**2"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "0.333*t**2 - 0.222*t + 0.074 + 0.926*exp(-3*t)"},

    # --- Stronger growth/decay ---
    {"ode_type": "linear", "f_expression": "5*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(5*t)"},
    {"ode_type": "linear", "f_expression": "-5*y"                , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(-5*t)"},
    {"ode_type": "linear", "f_expression": "0.1*y"               , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(0.1*t)"},
    {"ode_type": "linear", "f_expression": "-0.1*y"              , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(-0.1*t)"},

    # --- Log-type (non-zero t0) ---
    {"ode_type": "linear", "f_expression": "y/t"                 , "t0": 1, "y0":        1, "tf": 2, "exact_solution": "t"},
    {"ode_type": "linear", "f_expression": "-2*y/t"              , "t0": 1, "y0":        1, "tf": 2, "exact_solution": "1/t**2"},

    # --- Scaled trig / polynomial coefficients ---
    {"ode_type": "linear", "f_expression": "3*t*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(1.5*t**2)"},
    {"ode_type": "linear", "f_expression": "-3*t*y"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-1.5*t**2)"},
    {"ode_type": "linear", "f_expression": "4*cos(t)*y"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(4*sin(t))"},
    {"ode_type": "linear", "f_expression": "-4*cos(t)*y"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-4*sin(t))"},

    # --- High growth rates ---
    {"ode_type": "linear", "f_expression": "6*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(6*t)"},
    {"ode_type": "linear", "f_expression": "-6*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-6*t)"},
    {"ode_type": "linear", "f_expression": "7*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(7*t)"},
    {"ode_type": "linear", "f_expression": "-7*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-7*t)"},
    {"ode_type": "linear", "f_expression": "8*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(8*t)"},
    {"ode_type": "linear", "f_expression": "-8*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-8*t)"},
    {"ode_type": "linear", "f_expression": "9*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(9*t)"},
    {"ode_type": "linear", "f_expression": "-9*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-9*t)"},
    {"ode_type": "linear", "f_expression": "10*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(10*t)"},
    {"ode_type": "linear", "f_expression": "-10*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-10*t)"},

    # --- Constant RHS (pure integration) ---
    {"ode_type": "linear", "f_expression": "3"                   , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "3*t"},
    {"ode_type": "linear", "f_expression": "5"                   , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "5*t + 2"},
    {"ode_type": "linear", "f_expression": "-1"                  , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1 - t"},
    {"ode_type": "linear", "f_expression": "t"                   , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "t**2/2"},
    {"ode_type": "linear", "f_expression": "t**2"                , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "t**3/3"},
    {"ode_type": "linear", "f_expression": "2*t"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "t**2 + 1"},
    {"ode_type": "linear", "f_expression": "cos(t)"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "sin(t) + 1"},
    {"ode_type": "linear", "f_expression": "exp(t)"              , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "exp(t) - 1"},
    {"ode_type": "linear", "f_expression": "exp(-t)"             , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1 - exp(-t) + 1"},
    {"ode_type": "linear", "f_expression": "sin(2*t)"            , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "(1 - cos(2*t))/2"},
    {"ode_type": "linear", "f_expression": "cos(2*t)"            , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "sin(2*t)/2"},
    {"ode_type": "linear", "f_expression": "t**3"                , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "t**4/4"},
    {"ode_type": "linear", "f_expression": "2*t**2"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "2*t**3/3 + 1"},

    # --- Pure exponential: a*y with varied coefficients and y0 ---
    {"ode_type": "linear", "f_expression": "0.5*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(0.5*t)"},
    {"ode_type": "linear", "f_expression": "0.5*y"               , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(0.5*t)"},
    {"ode_type": "linear", "f_expression": "0.5*y"               , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(0.5*t)"},
    {"ode_type": "linear", "f_expression": "-0.5*y"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-0.5*t)"},
    {"ode_type": "linear", "f_expression": "-0.5*y"              , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(-0.5*t)"},
    {"ode_type": "linear", "f_expression": "2*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(2*t)"},
    {"ode_type": "linear", "f_expression": "2*y"                 , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(2*t)"},
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "3*y"                 , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(3*t)"},
    {"ode_type": "linear", "f_expression": "-3*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-3*t)"},
    {"ode_type": "linear", "f_expression": "4*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(4*t)"},
    {"ode_type": "linear", "f_expression": "4*y"                 , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(4*t)"},
    {"ode_type": "linear", "f_expression": "-4*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-4*t)"},
    {"ode_type": "linear", "f_expression": "-4*y"                , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(-4*t)"},
    {"ode_type": "linear", "f_expression": "5*y"                 , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(5*t)"},
    {"ode_type": "linear", "f_expression": "-5*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-5*t)"},
    {"ode_type": "linear", "f_expression": "-5*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-5*t)"},
    {"ode_type": "linear", "f_expression": "0.2*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(0.2*t)"},
    {"ode_type": "linear", "f_expression": "0.2*y"               , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(0.2*t)"},
    {"ode_type": "linear", "f_expression": "-0.2*y"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-0.2*t)"},
    {"ode_type": "linear", "f_expression": "-0.2*y"              , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(-0.2*t)"},
    {"ode_type": "linear", "f_expression": "0.4*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(0.4*t)"},
    {"ode_type": "linear", "f_expression": "-0.4*y"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-0.4*t)"},
    {"ode_type": "linear", "f_expression": "0.7*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(0.7*t)"},
    {"ode_type": "linear", "f_expression": "-0.7*y"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-0.7*t)"},
    {"ode_type": "linear", "f_expression": "1.5*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(1.5*t)"},
    {"ode_type": "linear", "f_expression": "-1.5*y"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-1.5*t)"},
    {"ode_type": "linear", "f_expression": "1.5*y"               , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(1.5*t)"},
    {"ode_type": "linear", "f_expression": "-1.5*y"              , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-1.5*t)"},
    {"ode_type": "linear", "f_expression": "2.5*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(2.5*t)"},
    {"ode_type": "linear", "f_expression": "-2.5*y"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-2.5*t)"},

    # --- Linear with constant forcing: a*y + b ---
    {"ode_type": "linear", "f_expression": "-y + 2"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "2 - exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y + 3"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "3 - 2*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y + 4"              , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "4 - 4*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-2*y + 1"            , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "0.5*(1 - exp(-2*t))"},
    {"ode_type": "linear", "f_expression": "-2*y + 2"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1 + 0*t"},
    {"ode_type": "linear", "f_expression": "-2*y + 4"            , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "2*(1 - exp(-2*t))"},
    {"ode_type": "linear", "f_expression": "2*y - 1"             , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "0.5 + 0.5*exp(2*t)"},
    {"ode_type": "linear", "f_expression": "y + 1"               , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "exp(t) - 1"},
    {"ode_type": "linear", "f_expression": "y + 2"               , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "2*exp(t) - 2"},
    {"ode_type": "linear", "f_expression": "-3*y + 3"            , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "1 - exp(-3*t)"},
    {"ode_type": "linear", "f_expression": "-3*y + 6"            , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "2*(1 - exp(-3*t))"},
    {"ode_type": "linear", "f_expression": "3*y + 3"             , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "exp(3*t) - 1"},

    # --- Linear with polynomial forcing (extended) ---
    {"ode_type": "linear", "f_expression": "y + t**2"            , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "exp(t) - t**2 - 2*t - 2"},
    {"ode_type": "linear", "f_expression": "-y + 2*t"            , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "2*t - 2 + 2*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y + t + 1"          , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "t - 1 + 1 + exp(-t) - 1"},
    {"ode_type": "linear", "f_expression": "-2*y + 2*t"          , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "t - 0.5 + 0.5*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "-2*y + t**2"         , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "0.5*t**2 - 0.5*t + 0.25*(1 - exp(-2*t))"},
    {"ode_type": "linear", "f_expression": "2*y + t**2"          , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "-0.5*t**2 - 0.5*t - 0.25 + 0.25*exp(2*t)"},
    {"ode_type": "linear", "f_expression": "-y + t**3"           , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "t**3 - 3*t**2 + 6*t - 6 + 6*exp(-t)"},

    # --- Trigonometric forcing ---
    {"ode_type": "linear", "f_expression": "-y + 2*sin(t)"       , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "sin(t) - cos(t) + exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y + 2*cos(t)"       , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "sin(t) + cos(t)"},
    {"ode_type": "linear", "f_expression": "-2*y + sin(t)"       , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "(1/5)*(-2*sin(t) - cos(t)) + (1/5)*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "y + sin(t)"          , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "0.5*(exp(t) - sin(t) - cos(t))"},
    {"ode_type": "linear", "f_expression": "y + cos(t)"          , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "0.5*(sin(t) + exp(t)) - 0.5*cos(t)"},

    # --- Exponential forcing (extended) ---
    {"ode_type": "linear", "f_expression": "-y + 2*exp(-t)"      , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "2*t*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y + exp(t)"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "t*exp(t) + exp(-t)"},
    {"ode_type": "linear", "f_expression": "-2*y + exp(-t)"      , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-t) - exp(-2*t) + exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "y - exp(-t)"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t) - t*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-3*y + exp(-3*t)"    , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "t*exp(-3*t)"},

    # --- t*y and t^2*y variations ---
    {"ode_type": "linear", "f_expression": "2*t*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t**2)"},
    {"ode_type": "linear", "f_expression": "-2*t*y"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-t**2)"},
    {"ode_type": "linear", "f_expression": "4*t*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(2*t**2)"},
    {"ode_type": "linear", "f_expression": "-4*t*y"              , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-2*t**2)"},
    {"ode_type": "linear", "f_expression": "0.5*t*y"             , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t**2/4)"},
    {"ode_type": "linear", "f_expression": "-0.5*t*y"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-t**2/4)"},
    {"ode_type": "linear", "f_expression": "t*y"                 , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(t**2/2)"},
    {"ode_type": "linear", "f_expression": "-t*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-t**2/2)"},
    {"ode_type": "linear", "f_expression": "2*t**2*y"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(2*t**3/3)"},
    {"ode_type": "linear", "f_expression": "-2*t**2*y"           , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-2*t**3/3)"},
    {"ode_type": "linear", "f_expression": "0.5*t**2*y"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t**3/6)"},
    {"ode_type": "linear", "f_expression": "-0.5*t**2*y"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-t**3/6)"},

    # --- Rational coefficient: y/(1+t) family ---
    {"ode_type": "linear", "f_expression": "y/(1+t)"             , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*(1+t)"},
    {"ode_type": "linear", "f_expression": "y/(1+t)"             , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*(1+t)"},
    {"ode_type": "linear", "f_expression": "-y/(1+t)"            , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2/(1+t)"},
    {"ode_type": "linear", "f_expression": "-y/(1+t)"            , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3/(1+t)"},
    {"ode_type": "linear", "f_expression": "2*y/(1+t)"           , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "(1+t)**2"},
    {"ode_type": "linear", "f_expression": "3*y/(1+t)"           , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "(1+t)**3"},
    {"ode_type": "linear", "f_expression": "-3*y/(1+t)"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1/(1+t)**3"},
    {"ode_type": "linear", "f_expression": "y/(3+t)"             , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*(3+t)/3"},

    # --- y/t family (non-zero t0) ---
    {"ode_type": "linear", "f_expression": "y/t"                 , "t0": 1, "y0":        2, "tf": 2, "exact_solution": "2*t"},
    {"ode_type": "linear", "f_expression": "y/t"                 , "t0": 1, "y0":        3, "tf": 2, "exact_solution": "3*t"},
    {"ode_type": "linear", "f_expression": "-y/t"                , "t0": 1, "y0":        1, "tf": 2, "exact_solution": "1/t"},
    {"ode_type": "linear", "f_expression": "-y/t"                , "t0": 1, "y0":        2, "tf": 2, "exact_solution": "2/t"},
    {"ode_type": "linear", "f_expression": "2*y/t"               , "t0": 1, "y0":        1, "tf": 2, "exact_solution": "t**2"},
    {"ode_type": "linear", "f_expression": "3*y/t"               , "t0": 1, "y0":        1, "tf": 2, "exact_solution": "t**3"},
    {"ode_type": "linear", "f_expression": "-3*y/t"              , "t0": 1, "y0":        1, "tf": 2, "exact_solution": "1/t**3"},
    {"ode_type": "linear", "f_expression": "4*y/t"               , "t0": 1, "y0":        1, "tf": 2, "exact_solution": "t**4"},
    {"ode_type": "linear", "f_expression": "-4*y/t"              , "t0": 1, "y0":        1, "tf": 2, "exact_solution": "1/t**4"},

    # --- Trig-coefficient variations ---
    {"ode_type": "linear", "f_expression": "sin(t)*y"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(1-cos(t))"},
    {"ode_type": "linear", "f_expression": "-2*sin(t)*y"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(2*cos(t)-2)"},
    {"ode_type": "linear", "f_expression": "2*sin(t)*y"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(2*(1-cos(t)))"},
    {"ode_type": "linear", "f_expression": "3*cos(t)*y"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(3*sin(t))"},
    {"ode_type": "linear", "f_expression": "-3*cos(t)*y"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-3*sin(t))"},
    {"ode_type": "linear", "f_expression": "5*cos(t)*y"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(5*sin(t))"},
    {"ode_type": "linear", "f_expression": "-5*cos(t)*y"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-5*sin(t))"},
    {"ode_type": "linear", "f_expression": "sin(2*t)*y"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-(cos(2*t)-1)/2)"},
    {"ode_type": "linear", "f_expression": "-sin(2*t)*y"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp((cos(2*t)-1)/2)"},
    {"ode_type": "linear", "f_expression": "cos(2*t)*y"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(sin(2*t)/2)"},
    {"ode_type": "linear", "f_expression": "-cos(2*t)*y"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-sin(2*t)/2)"},

    # --- (1+t)*y and related polynomial coefficients ---
    {"ode_type": "linear", "f_expression": "(2+t)*y"             , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(2*t + t**2/2)"},
    {"ode_type": "linear", "f_expression": "-(1+t)*y"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-(t + t**2/2))"},
    {"ode_type": "linear", "f_expression": "-(2+t)*y"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-(2*t + t**2/2))"},
    {"ode_type": "linear", "f_expression": "(1+2*t)*y"           , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t + t**2)"},
    {"ode_type": "linear", "f_expression": "-(1+2*t)*y"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-(t + t**2))"},

    # --- Varied initial conditions ---
    {"ode_type": "linear", "f_expression": "y"                   , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(t)"},
    {"ode_type": "linear", "f_expression": "y"                   , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(t)"},
    {"ode_type": "linear", "f_expression": "y"                   , "t0": 0, "y0":      0.5, "tf": 1, "exact_solution": "0.5*exp(t)"},
    {"ode_type": "linear", "f_expression": "-y"                  , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y"                  , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y"                  , "t0": 0, "y0":      0.5, "tf": 1, "exact_solution": "0.5*exp(-t)"},

    # --- Wider time range (tf=2) ---
    {"ode_type": "linear", "f_expression": "-y"                  , "t0": 0, "y0":        1, "tf": 2, "exact_solution": "exp(-t)"},
    {"ode_type": "linear", "f_expression": "y"                   , "t0": 0, "y0":        1, "tf": 2, "exact_solution": "exp(t)"},
    {"ode_type": "linear", "f_expression": "-0.5*y"              , "t0": 0, "y0":        1, "tf": 2, "exact_solution": "exp(-0.5*t)"},
    {"ode_type": "linear", "f_expression": "0.5*y"               , "t0": 0, "y0":        1, "tf": 2, "exact_solution": "exp(0.5*t)"},
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 0, "y0":        1, "tf": 2, "exact_solution": "exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "2*y"                 , "t0": 0, "y0":        1, "tf": 2, "exact_solution": "exp(2*t)"},
    {"ode_type": "linear", "f_expression": "-y + 1"              , "t0": 0, "y0":        0, "tf": 2, "exact_solution": "1 - exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y + t"              , "t0": 0, "y0":        0, "tf": 2, "exact_solution": "t - 1 + exp(-t)"},
    {"ode_type": "linear", "f_expression": "t*y"                 , "t0": 0, "y0":        1, "tf": 2, "exact_solution": "exp(t**2/2)"},
    {"ode_type": "linear", "f_expression": "-t*y"                , "t0": 0, "y0":        1, "tf": 2, "exact_solution": "exp(-t**2/2)"},
    {"ode_type": "linear", "f_expression": "cos(t)*y"            , "t0": 0, "y0":        1, "tf": 2, "exact_solution": "exp(sin(t))"},
    {"ode_type": "linear", "f_expression": "-cos(t)*y"           , "t0": 0, "y0":        1, "tf": 2, "exact_solution": "exp(-sin(t))"},

    # --- Different step size h=0.05 ---
    {"ode_type": "linear", "f_expression": "-y"                  , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-t)"},
    {"ode_type": "linear", "f_expression": "y"                   , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t)"},
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "2*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(2*t)"},
    {"ode_type": "linear", "f_expression": "-y + 1"              , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "1 - exp(-t)"},
    {"ode_type": "linear", "f_expression": "t*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t**2/2)"},
    {"ode_type": "linear", "f_expression": "cos(t)*y"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(sin(t))"},
    {"ode_type": "linear", "f_expression": "-y + sin(t)"         , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "0.5*(sin(t) - cos(t)) + 0.5*exp(-t)"},

    # --- Different step size h=0.001 ---
    {"ode_type": "linear", "f_expression": "-y"                  , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-t)"},
    {"ode_type": "linear", "f_expression": "y"                   , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t)"},
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "2*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(2*t)"},
    {"ode_type": "linear", "f_expression": "t*y"                 , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t**2/2)"},

    # --- Stiff-like (large coefficients) ---
    {"ode_type": "linear", "f_expression": "-20*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-20*t)"},
    {"ode_type": "linear", "f_expression": "-15*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-15*t)"},
    {"ode_type": "linear", "f_expression": "-12*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-12*t)"},
    {"ode_type": "linear", "f_expression": "-11*y"               , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-11*t)"},
    {"ode_type": "linear", "f_expression": "11*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(11*t)"},
    {"ode_type": "linear", "f_expression": "12*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(12*t)"},
    {"ode_type": "linear", "f_expression": "15*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(15*t)"},
    {"ode_type": "linear", "f_expression": "20*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(20*t)"},

    # --- Non-zero t0 cases ---
    {"ode_type": "linear", "f_expression": "-y"                  , "t0": 1, "y0": 0.367879, "tf": 2, "exact_solution": "exp(-t)"},
    {"ode_type": "linear", "f_expression": "y"                   , "t0": 1, "y0": 2.718282, "tf": 2, "exact_solution": "exp(t)"},
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 1, "y0": 0.135335, "tf": 2, "exact_solution": "exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "2*y"                 , "t0": 1, "y0": 7.389056, "tf": 2, "exact_solution": "exp(2*t)"},
    {"ode_type": "linear", "f_expression": "t*y"                 , "t0": 1, "y0": 1.648721, "tf": 2, "exact_solution": "exp(t**2/2)"},

    # --- Mixed forcing functions ---
    {"ode_type": "linear", "f_expression": "-y + t**2 + 2*t"     , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "t**2 + 3*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-2*y + 4*t"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "2*t - 1 + 2*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "-y + exp(-2*t)"      , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "-exp(-2*t) + 2*exp(-t)"},
    {"ode_type": "linear", "f_expression": "y - 2*t"             , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "2*t + 2 - exp(t)"},
    {"ode_type": "linear", "f_expression": "-3*y + 9*t"          , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "3*t - 1 + exp(-3*t)"},
    {"ode_type": "linear", "f_expression": "2*y - 2"             , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "1 + exp(2*t)"},
    {"ode_type": "linear", "f_expression": "-4*y + 8"            , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "2 - exp(-4*t)"},
    {"ode_type": "linear", "f_expression": "-y + 4*t**2"         , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "4*t**2 - 8*t + 8 - 8*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y + cos(2*t)"       , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "(2*sin(2*t) + cos(2*t) - exp(-t))/5"},
    {"ode_type": "linear", "f_expression": "-y + sin(2*t)"       , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "(-cos(2*t) + 2*sin(2*t) - 2*exp(-t))/5"},
    {"ode_type": "linear", "f_expression": "-2*y + cos(t)"       , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "(2*cos(t)+sin(t))/5 + (1 - 2/5)*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "-2*y + sin(t)"       , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "(2*sin(t)-cos(t)+exp(-2*t))/5"},

    # --- Additional y0 variants ---
    {"ode_type": "linear", "f_expression": "-y"                  , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y"                  , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(-t)"},
    {"ode_type": "linear", "f_expression": "y"                   , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(t)"},
    {"ode_type": "linear", "f_expression": "y"                   , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(t)"},
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "2*y"                 , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(2*t)"},
    {"ode_type": "linear", "f_expression": "2*y"                 , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(2*t)"},
    {"ode_type": "linear", "f_expression": "3*y"                 , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(3*t)"},
    {"ode_type": "linear", "f_expression": "-3*y"                , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(-3*t)"},
    {"ode_type": "linear", "f_expression": "4*y"                 , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(4*t)"},
    {"ode_type": "linear", "f_expression": "-4*y"                , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(-4*t)"},
    {"ode_type": "linear", "f_expression": "-5*y"                , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(-5*t)"},
    {"ode_type": "linear", "f_expression": "5*y"                 , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(5*t)"},
    {"ode_type": "linear", "f_expression": "-6*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-6*t)"},
    {"ode_type": "linear", "f_expression": "6*y"                 , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(6*t)"},
    {"ode_type": "linear", "f_expression": "-7*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-7*t)"},
    {"ode_type": "linear", "f_expression": "7*y"                 , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(7*t)"},
    {"ode_type": "linear", "f_expression": "-8*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-8*t)"},
    {"ode_type": "linear", "f_expression": "8*y"                 , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(8*t)"},

    # --- Wider time range (tf=3) ---
    {"ode_type": "linear", "f_expression": "-y"                  , "t0": 0, "y0":        1, "tf": 3, "exact_solution": "exp(-t)"},
    {"ode_type": "linear", "f_expression": "y"                   , "t0": 0, "y0":        1, "tf": 3, "exact_solution": "exp(t)"},
    {"ode_type": "linear", "f_expression": "-0.5*y"              , "t0": 0, "y0":        1, "tf": 3, "exact_solution": "exp(-0.5*t)"},
    {"ode_type": "linear", "f_expression": "-y + 1"              , "t0": 0, "y0":        0, "tf": 3, "exact_solution": "1 - exp(-t)"},

    # --- Rational / squared-coefficient ODEs ---
    {"ode_type": "linear", "f_expression": "-(1+t**2)*y"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(-(t + t**3/3))"},
    {"ode_type": "linear", "f_expression": "(1+t**2)*y"          , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t + t**3/3)"},
    {"ode_type": "linear", "f_expression": "-t/(1+t**2)*y"       , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1/sqrt(1+t**2)"},
    {"ode_type": "linear", "f_expression": "t/(1+t**2)*y"        , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "sqrt(1+t**2)"},

    # --- Extra exponential forcing ---
    {"ode_type": "linear", "f_expression": "-2*y + exp(-2*t)"    , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "t*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "-y + 2*exp(-t)"      , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "(2*t+1)*exp(-t)"},
    {"ode_type": "linear", "f_expression": "y + exp(-t)"         , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "exp(t) - t*exp(-t)"},
    {"ode_type": "linear", "f_expression": "-y + exp(2*t)"       , "t0": 0, "y0":        0, "tf": 1, "exact_solution": "(exp(2*t) - exp(-t))/3"},

    # --- Padding (a*y with matching y0) ---
    {"ode_type": "linear", "f_expression": "-10*y"               , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(-10*t)"},
    {"ode_type": "linear", "f_expression": "-1*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1*exp(-1*t)"},
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "-3*y"                , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(-3*t)"},
    {"ode_type": "linear", "f_expression": "-4*y"                , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(-4*t)"},
    {"ode_type": "linear", "f_expression": "-5*y"                , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(-5*t)"},
    {"ode_type": "linear", "f_expression": "-6*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1*exp(-6*t)"},
    {"ode_type": "linear", "f_expression": "-7*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-7*t)"},
    {"ode_type": "linear", "f_expression": "-8*y"                , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(-8*t)"},
    {"ode_type": "linear", "f_expression": "-9*y"                , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(-9*t)"},
    {"ode_type": "linear", "f_expression": "-10*y"               , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(-10*t)"},
    {"ode_type": "linear", "f_expression": "-1*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1*exp(-1*t)"},
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "-3*y"                , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(-3*t)"},
    {"ode_type": "linear", "f_expression": "-4*y"                , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(-4*t)"},
    {"ode_type": "linear", "f_expression": "-5*y"                , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(-5*t)"},
    {"ode_type": "linear", "f_expression": "-6*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1*exp(-6*t)"},
    {"ode_type": "linear", "f_expression": "-7*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-7*t)"},
    {"ode_type": "linear", "f_expression": "-8*y"                , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(-8*t)"},
    {"ode_type": "linear", "f_expression": "-9*y"                , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(-9*t)"},
    {"ode_type": "linear", "f_expression": "-10*y"               , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(-10*t)"},
    {"ode_type": "linear", "f_expression": "-1*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1*exp(-1*t)"},
    {"ode_type": "linear", "f_expression": "-2*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-2*t)"},
    {"ode_type": "linear", "f_expression": "-3*y"                , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(-3*t)"},
    {"ode_type": "linear", "f_expression": "-4*y"                , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(-4*t)"},
    {"ode_type": "linear", "f_expression": "-5*y"                , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(-5*t)"},
    {"ode_type": "linear", "f_expression": "-6*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1*exp(-6*t)"},
    {"ode_type": "linear", "f_expression": "-7*y"                , "t0": 0, "y0":        2, "tf": 1, "exact_solution": "2*exp(-7*t)"},
    {"ode_type": "linear", "f_expression": "-8*y"                , "t0": 0, "y0":        3, "tf": 1, "exact_solution": "3*exp(-8*t)"},
    {"ode_type": "linear", "f_expression": "-9*y"                , "t0": 0, "y0":        4, "tf": 1, "exact_solution": "4*exp(-9*t)"},
    {"ode_type": "linear", "f_expression": "-10*y"               , "t0": 0, "y0":        5, "tf": 1, "exact_solution": "5*exp(-10*t)"},
    {"ode_type": "linear", "f_expression": "-1*y"                , "t0": 0, "y0":        1, "tf": 1, "exact_solution": "1*exp(-1*t)"},
]

print("successfully run")